# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import medeasy_minimal_pb2 as medeasy__minimal__pb2

GRPC_GENERATED_VERSION = '1.68.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in medeasy_minimal_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MedEasyServiceStub(object):
    """Minimal MedEasy Service for testing
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAvailableModels = channel.unary_unary(
                '/medeasy.MedEasyService/GetAvailableModels',
                request_serializer=medeasy__minimal__pb2.GetAvailableModelsRequest.SerializeToString,
                response_deserializer=medeasy__minimal__pb2.GetAvailableModelsResponse.FromString,
                _registered_method=True)
        self.GetHardwareInfo = channel.unary_unary(
                '/medeasy.MedEasyService/GetHardwareInfo',
                request_serializer=medeasy__minimal__pb2.GetHardwareInfoRequest.SerializeToString,
                response_deserializer=medeasy__minimal__pb2.GetHardwareInfoResponse.FromString,
                _registered_method=True)
        self.Transcribe = channel.unary_unary(
                '/medeasy.MedEasyService/Transcribe',
                request_serializer=medeasy__minimal__pb2.TranscriptionRequest.SerializeToString,
                response_deserializer=medeasy__minimal__pb2.TranscriptionResponse.FromString,
                _registered_method=True)
        self.BenchmarkModels = channel.unary_unary(
                '/medeasy.MedEasyService/BenchmarkModels',
                request_serializer=medeasy__minimal__pb2.BenchmarkModelsRequest.SerializeToString,
                response_deserializer=medeasy__minimal__pb2.BenchmarkModelsResponse.FromString,
                _registered_method=True)


class MedEasyServiceServicer(object):
    """Minimal MedEasy Service for testing
    """

    def GetAvailableModels(self, request, context):
        """Get available Whisper models
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetHardwareInfo(self, request, context):
        """Get hardware information
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Transcribe(self, request, context):
        """Transcribe audio to text
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BenchmarkModels(self, request, context):
        """Benchmark Whisper models
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MedEasyServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAvailableModels': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAvailableModels,
                    request_deserializer=medeasy__minimal__pb2.GetAvailableModelsRequest.FromString,
                    response_serializer=medeasy__minimal__pb2.GetAvailableModelsResponse.SerializeToString,
            ),
            'GetHardwareInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHardwareInfo,
                    request_deserializer=medeasy__minimal__pb2.GetHardwareInfoRequest.FromString,
                    response_serializer=medeasy__minimal__pb2.GetHardwareInfoResponse.SerializeToString,
            ),
            'Transcribe': grpc.unary_unary_rpc_method_handler(
                    servicer.Transcribe,
                    request_deserializer=medeasy__minimal__pb2.TranscriptionRequest.FromString,
                    response_serializer=medeasy__minimal__pb2.TranscriptionResponse.SerializeToString,
            ),
            'BenchmarkModels': grpc.unary_unary_rpc_method_handler(
                    servicer.BenchmarkModels,
                    request_deserializer=medeasy__minimal__pb2.BenchmarkModelsRequest.FromString,
                    response_serializer=medeasy__minimal__pb2.BenchmarkModelsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'medeasy.MedEasyService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('medeasy.MedEasyService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MedEasyService(object):
    """Minimal MedEasy Service for testing
    """

    @staticmethod
    def GetAvailableModels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/medeasy.MedEasyService/GetAvailableModels',
            medeasy__minimal__pb2.GetAvailableModelsRequest.SerializeToString,
            medeasy__minimal__pb2.GetAvailableModelsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetHardwareInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/medeasy.MedEasyService/GetHardwareInfo',
            medeasy__minimal__pb2.GetHardwareInfoRequest.SerializeToString,
            medeasy__minimal__pb2.GetHardwareInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Transcribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/medeasy.MedEasyService/Transcribe',
            medeasy__minimal__pb2.TranscriptionRequest.SerializeToString,
            medeasy__minimal__pb2.TranscriptionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BenchmarkModels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/medeasy.MedEasyService/BenchmarkModels',
            medeasy__minimal__pb2.BenchmarkModelsRequest.SerializeToString,
            medeasy__minimal__pb2.BenchmarkModelsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
